db.manager:
    path:     /
    defaults: { _controller: DBManagerBundle:Manage:index }

db.manager.list:
    path:     /{name}
    defaults: { _controller: DBManagerBundle:Manage:list }

db.manager.process:
    path:     /process/{method}/{name}/{id}
    defaults: { _controller: DBManagerBundle:Manage:process, id: -1}
    requirements:
            page: '\d+'